
services:
  mysql:
    image: mysql:8.0
    container_name: hichat-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hichat-network
    restart: always  

  redis:
    image: redis:6.0
    container_name: hichat-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - hichat-network
    restart: always  

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hichat-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin  # 设置默认用户名
      RABBITMQ_DEFAULT_PASS: admin  # 设置默认密码
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - hichat-network
    restart: always  

  consul:
    image: consul:1.10
    container_name: hichat-consul
    ports:
      - "9500:8500"
    networks:
      - hichat-network
    restart: always  

  traefik:
    image: traefik:v3.2.0
    container_name: traefik
    command: --api.insecure=true --providers.docker --configFile=/etc/traefik/traefik.toml
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "8080:8080"  # Dashboard
    volumes:
      - ./traefik:/etc/traefik  # 挂载 traefik.toml 配置文件
      - /var/run/docker.sock:/var/run/docker.sock  # 使 Traefik 能够监控 Docker 容器
    networks:
      - hichat-network
    restart: always  
    depends_on:
      - consul

  hichat-ws1-service:
    image: hyyyh/hichat-ws-service:latest  
    container_name: hichat-ws1-service
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - consul
    ports:
      - "3003:3003"
    networks:
      - hichat-network
    restart: always  
    labels:
      - "traefik.http.routers.ws.rule=Host(`ws.docker.localhost`)"  # Traefik 路由规则

  hichat-ws2-service:
    image: hyyyh/hichat-ws-service:latest  
    container_name: hichat-ws2-service
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - consul
    ports:
      - "3004:3004"
    networks:
      - hichat-network
    restart: always  
    labels:
      - "traefik.http.routers.ws.rule=Host(`ws.docker.localhost`)"  # Traefik 路由规则

  hichat-mq-service:
    image: hyyyh/hichat-mq-service:latest  
    container_name: hichat-mq-service
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - consul
    ports:
      - "3008:3008"
    networks:
      - hichat-network
    restart: always  
    labels:
      - "traefik.http.routers.mq.rule=Host(`mq.docker.localhost`)"  # Traefik 路由规则
      


  hichat-static-service:
    image: hyyyh/hichat-static-service:latest  
    container_name: hichat-static-service
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - consul
    ports:
      - "3005:3005"
    networks:
      - hichat-network
    restart: always  
    labels:
      - "traefik.http.routers.static.rule=Host(`static.docker.localhost`)"  # Traefik 路由规则
      
  hichat-file-service:
    image: hyyyh/hichat-file-service:latest  
    container_name: hichat-file-service
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - consul
    ports:
      - "3006:3006"
    networks:
      - hichat-network
    restart: always  
    labels:
      - "traefik.http.routers.file.rule=Host(`file.docker.localhost`)"  # Traefik 路由规则
      
  hichat-stream-service:
    image: hyyyh/hichat-streammedia-service:latest  
    container_name: hichat-streammedia-service
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - consul
    ports:
      - "3009:3009"
      - "50052:50052"
    networks:
      - hichat-network
    restart: always  
    labels:
      - "traefik.http.routers.stream.rule=Host(`streammedia.docker.localhost`)"  # Traefik 路由规则
      

volumes:
  mysql-data:
  redis-data:

networks:
  hichat-network:
    driver: bridge
