FROM golang:alpine
ENV GOPROXY https://goproxy.cn,direct

WORKDIR  /app
COPY go.mod ./
COPY go.sum ./


RUN go mod download

COPY . .

RUN go build -o hichat_streammedia_server .

EXPOSE 3009
EXPOSE 50052

CMD ["./hichat_streammedia_server", "-d", "docker"]