// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: noticevideostreamserver.proto

// 定义包名

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Noticevideostreamserverreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartUserid     int32  `protobuf:"varint,1,opt,name=start_userid,json=startUserid,proto3" json:"start_userid,omitempty"`
	StartUsername   string `protobuf:"bytes,2,opt,name=start_username,json=startUsername,proto3" json:"start_username,omitempty"`
	ReceiveUserid   int32  `protobuf:"varint,3,opt,name=receive_userid,json=receiveUserid,proto3" json:"receive_userid,omitempty"`
	ReceiveUsername string `protobuf:"bytes,4,opt,name=receive_username,json=receiveUsername,proto3" json:"receive_username,omitempty"`
}

func (x *Noticevideostreamserverreq) Reset() {
	*x = Noticevideostreamserverreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noticevideostreamserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Noticevideostreamserverreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Noticevideostreamserverreq) ProtoMessage() {}

func (x *Noticevideostreamserverreq) ProtoReflect() protoreflect.Message {
	mi := &file_noticevideostreamserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Noticevideostreamserverreq.ProtoReflect.Descriptor instead.
func (*Noticevideostreamserverreq) Descriptor() ([]byte, []int) {
	return file_noticevideostreamserver_proto_rawDescGZIP(), []int{0}
}

func (x *Noticevideostreamserverreq) GetStartUserid() int32 {
	if x != nil {
		return x.StartUserid
	}
	return 0
}

func (x *Noticevideostreamserverreq) GetStartUsername() string {
	if x != nil {
		return x.StartUsername
	}
	return ""
}

func (x *Noticevideostreamserverreq) GetReceiveUserid() int32 {
	if x != nil {
		return x.ReceiveUserid
	}
	return 0
}

func (x *Noticevideostreamserverreq) GetReceiveUsername() string {
	if x != nil {
		return x.ReceiveUsername
	}
	return ""
}

type Noticevideostreamserverres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg_model,proto3" json:"msg,omitempty"`
}

func (x *Noticevideostreamserverres) Reset() {
	*x = Noticevideostreamserverres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_noticevideostreamserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Noticevideostreamserverres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Noticevideostreamserverres) ProtoMessage() {}

func (x *Noticevideostreamserverres) ProtoReflect() protoreflect.Message {
	mi := &file_noticevideostreamserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Noticevideostreamserverres.ProtoReflect.Descriptor instead.
func (*Noticevideostreamserverres) Descriptor() ([]byte, []int) {
	return file_noticevideostreamserver_proto_rawDescGZIP(), []int{1}
}

func (x *Noticevideostreamserverres) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Noticevideostreamserverres) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_noticevideostreamserver_proto protoreflect.FileDescriptor

var file_noticevideostreamserver_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x01, 0x0a, 0x1a, 0x6e, 0x6f, 0x74, 0x69, 0x63,
	0x65, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x72, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x25, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x46, 0x0a, 0x1a, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x72, 0x65, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x77, 0x0a, 0x12, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x61, 0x0a, 0x17, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x72, 0x65, 0x71, 0x1a, 0x21, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x72, 0x65, 0x73,
	0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_noticevideostreamserver_proto_rawDescOnce sync.Once
	file_noticevideostreamserver_proto_rawDescData = file_noticevideostreamserver_proto_rawDesc
)

func file_noticevideostreamserver_proto_rawDescGZIP() []byte {
	file_noticevideostreamserver_proto_rawDescOnce.Do(func() {
		file_noticevideostreamserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_noticevideostreamserver_proto_rawDescData)
	})
	return file_noticevideostreamserver_proto_rawDescData
}

var file_noticevideostreamserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_noticevideostreamserver_proto_goTypes = []interface{}{
	(*Noticevideostreamserverreq)(nil), // 0: proto.noticevideostreamserverreq
	(*Noticevideostreamserverres)(nil), // 1: proto.noticevideostreamserverres
}
var file_noticevideostreamserver_proto_depIdxs = []int32{
	0, // 0: proto.videostreamservice.noticevideostreamserver:input_type -> proto.noticevideostreamserverreq
	1, // 1: proto.videostreamservice.noticevideostreamserver:output_type -> proto.noticevideostreamserverres
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_noticevideostreamserver_proto_init() }
func file_noticevideostreamserver_proto_init() {
	if File_noticevideostreamserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_noticevideostreamserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Noticevideostreamserverreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_noticevideostreamserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Noticevideostreamserverres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_noticevideostreamserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noticevideostreamserver_proto_goTypes,
		DependencyIndexes: file_noticevideostreamserver_proto_depIdxs,
		MessageInfos:      file_noticevideostreamserver_proto_msgTypes,
	}.Build()
	File_noticevideostreamserver_proto = out.File
	file_noticevideostreamserver_proto_rawDesc = nil
	file_noticevideostreamserver_proto_goTypes = nil
	file_noticevideostreamserver_proto_depIdxs = nil
}
