# syntax=docker/dockerfile:1

FROM golang:alpine

# 创建一个工作目录，之后源码或编译产物都存放在该目录中
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
ENV GOPROXY https://proxy.golang.com.cn,direct

RUN go mod download

COPY *.go ./
COPY ADB ./ADB
COPY config ./config
COPY models ./models
COPY service_registry ./service_registry
COPY util ./util

RUN go build -o hichat-mq-service .

EXPOSE 3008

CMD ["./hichat-mq-service", "-d", "docker"]