FROM golang:alpine
ENV GOPROXY https://goproxy.cn,direct

WORKDIR  /app
COPY go.mod ./
COPY go.sum ./


RUN go mod download

COPY . .

RUN go build -o hichat_ws_server .

EXPOSE 3004

CMD ["./hichat_ws_server", "-d", "docker"]